name: Run examples

on:
  pull_request:
    paths-ignore:
      - "*.md"
      - "**/*.md"
      - "LICENSE*"
env:
  CONTAINER_NAME: onediff-test
  REGION_ID: cn-beijing
  ACR_ORG: registry.cn-beijing.aliyuncs.com/oneflow

concurrency:
  group: sd-examples-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-examples:
    name: "Examples ${{ matrix.image }}"
    runs-on: [self-hosted, gpu]
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        image:
          - onediff:cu118
          - onediff-pro:cu121
    steps:
      - name: Login to ACR with the AccessKey pair
        uses: aliyun/acr-login@v1
        with:
          login-server: https://registry.${{env.REGION_ID}}.aliyuncs.com
          username: "${{ secrets.ACR_USERNAME }}"
          password: "${{ secrets.ACR_PASSWORD }}"
      - name: Setup docker
        run: |
          docker rm -f ${{ env.CONTAINER_NAME }} || true
          docker pull ${{ env.ACR_ORG }}/${{ matrix.image }}
          docker run --rm --gpus=all -d --privileged --shm-size=8g \
            --pids-limit 2000 \
            --cap-add=SYS_PTRACE --security-opt seccomp=unconfined \
            -v $HOME/test-container-cache-${{ env.CONTAINER_NAME }}/dot-local:/root/.local \
            -v $HOME/test-container-cache-${{ env.CONTAINER_NAME }}/dot-cache:/root/.cache \
            -v /share_nfs:/share_nfs:ro \
            -v $PWD:/src/onediff \
            -w /src/onediff \
            -e HF_HUB_OFFLINE=1 \
            --name ${{ env.CONTAINER_NAME }} \
            ${{ env.ACR_ORG }}/${{ matrix.image }} \
            sleep 5400
          docker exec ${{ env.CONTAINER_NAME }} rm -rf *
      - name: Checkout
        uses: actions/checkout@v4
      - run: nvidia-smi
      - run: nvidia-smi -L
      - run: docker exec ${{ env.CONTAINER_NAME }} python3 examples/text_to_image.py --model_id=/share_nfs/hf_models/stable-diffusion-v1-5
      - run: docker exec ${{ env.CONTAINER_NAME }} python3 examples/image_to_image.py --model_id=/share_nfs/hf_models/stable-diffusion-2-1
      - run: docker exec ${{ env.CONTAINER_NAME }} python3 examples/text_to_image_sdxl.py --base /share_nfs/hf_models/stable-diffusion-xl-base-1.0 --compile_vae False --height 512 --width 512 --use_multiple_resolutions True
      - run: docker exec ${{ env.CONTAINER_NAME }} python3 examples/text_to_image_sdxl.py --base /share_nfs/hf_models/stable-diffusion-xl-base-1.0 --compile_unet False --height 512 --width 512 --use_multiple_resolutions True
      - run: docker exec ${{ env.CONTAINER_NAME }} python3 benchmarks/stable_diffusion_2_unet.py --model_id=/share_nfs/hf_models/stable-diffusion-2-1
      - run: docker exec ${{ env.CONTAINER_NAME }} bash examples/unet_save_and_load.sh --model_id=/share_nfs/hf_models/stable-diffusion-2-1
